#!/usr/bin/env ruby

$:.unshift File.join(File.dirname(__FILE__), "../lib")
require 'optparse'
require 'fcntl' # STDIN
require 'toycipher'
require 'pp'

CIPHERS = ToyCipher::CIPHERS
class OptParseToyCipher
  def self.parse args
    begin
      options = { }
      ciphers = CIPHERS.sort * ', '
      option_parser = OptionParser.new do |opts|
        opts.banner = "ToyCipher: A utility for encryption & decryption with classic ciphers"
        opts.on("--debug", "Debug mode") { options[:debug] = true }
        opts.on("-h", "--help", "Print this help screen") { puts opts; exit 0; }
        opts.on("-a", "--analysis", "Print frequency analysis") { options[:analysis] = true }
        opts.on("-f", "--fill letter", "Fill letter for digraphs (playfair), X otherwise") { |fill|
          puts "Set options[:fill] to #{fill}" if options[:debug]
          options[:fill] = fill
        }
        opts.on("-k", "--key key(s)", "Encryption Key(s) separated by ','") { |k| 
          puts "Set key to '#{k}'" if options[:debug]
          options[:key] = k 
        }
        opts.on("-o", "--output-file [file]", "Output file for results, defaults to STDOUT") do |f| 
          options[:outfile] = f 
        end 
        opts.on("-i", "--input-file file", "Input file for encryption or decryption") do |f|
          options[:infile] = f
        end 
        opts.on("--demo", "Example Ciphers") { options[:demo] = true }
        opts.on("-d", "--decrypt cipher", CIPHERS, "Decrypt ciphertext with cipher") do |c| 
          options[:cipher] = c 
          options[:cipher][0] = c[0].chr.upcase # :(
          options[:decrypt] = options[:cipher] 
        end 
        opts.on("-e", "--encrypt cipher", CIPHERS, "Encrypt plaintext with cipher") do |c| 
          options[:cipher] = c
          options[:cipher][0] = c[0].chr.upcase # :(
          options[:encrypt] = options[:cipher]
        end 
        opts.on("-p", "--pretty", "Pretty output by replacing Z with space") { 
          options[:pretty] = true }
        opts.on("-c", "--ciphers", CIPHERS, "List of Ciphers:", "(#{ciphers})") do |c| 
          options[:cipher] = c 
          options[:cipher][0] = c[0].chr.upcase # :(
        end
        opts.on("-t", "--transpose", "Transpose m x n lines of text to be n x m") do
          options[:transpose] = true
        end
        opts.on("-v", "--verbose", "Verbose setting") { options[:verbose] = true }
        opts.on("-V", "--version", "Show version info") { puts "#{ToyCipher::VERSION_STR}"; exit 0; }
      end
      option_parser.parse!(args)
      options
    rescue OptionParser::ParseError => error
      puts error.message
      exit -1
    end
  end
end

@options = OptParseToyCipher.parse ARGV
puts "options: #{@options.inspect}" if @options[:debug]
puts "ARGV after parse: #{ARGV}" if @options[:debug]
@input = ARGV.shift
#@options[:plaintext] ||= @input if @input
puts "@input after parse: #{@input}" if @options[:debug]

# Read STDIN
@stdin = STDIN.read if STDIN.fcntl(Fcntl::F_GETFL, 0) == 0
puts "STDIN: #{@stdin.to_s}" if @options[:debug]

if cipher = @options[:encrypt]
  raise "No cipher specified!  Expected one of #{CIPHERS * ', '}" unless CIPHERS.include?(cipher.downcase)
  @options[:plaintext] ||= @stdin if @stdin
  @options[:plaintext] ||= @input if @input
elsif cipher = @options[:decrypt]
  raise "No cipher specified!  Expected one of #{CIPHERS * ', '}" unless CIPHERS.include?(cipher.downcase)
  @options[:ciphertext] ||= @stdin if @stdin
  @options[:ciphertext] ||= @input if @input
end

if @options[:transpose] && @input
  @transposed = @input.split("\n")
end

if keys = @options[:key]
  keys.split(',').each { |k| (@keys ||= []) << k.strip }
end
#puts "keys: #{@keys}"

def print_result(results)
  results.each do |result|
    # Pretty output by guessing that 'Z' (fill letter for playfair) is a space (risky)
    if @options[:pretty]
      case @options[:cipher]
      when /playfair/i
        result.gsub!(' ', '')
        result.gsub!(/#{@options[:fill] || 'x'}/i, '')
      end
      result.gsub!(/z/i, ' ')
    end
    #puts "result: #{result}"
    (@all_results ||= []) << result
  end

  if @options[:outfile]
    File.open(@options[:outfile], 'w') { |f| f << @all_results * "\n" }
  else
    STDOUT.puts @all_results * "\n"
  end
end

def prepare_input_file
  stream = IO.readlines(@options[:infile])
  n_rows = stream.size
  stream = stream.map { |l| l.chomp }.join
  #puts "stream: #{stream}"
  #puts "options[:plaintext]: #{@options[:plaintext].class}"
  @options[:ciphertext] = stream if @options[:decrypt]
  @options[:plaintext] = stream if @options[:encrypt]
end

prepare_input_file if @options[:infile]
pp @options if @options[:debug]

if @options[:key]
  @keys.each do |k|
    @cipher = instance_eval "ToyCipher::#{@options[:cipher]}.new" # shouldn't have to do this per key
    if @options[:fill]
      puts "Fill letter set to #{@options[:fill]}" if @options[:debug]
      @cipher.set_fill_letter @options[:fill] if @cipher.respond_to?(:set_fill_letter)
    end
    
    puts "Running on key: #{k}" if @options[:verbose]
    begin
      @result =
        if @options[:plaintext]
          @cipher.encrypt(@options[:plaintext], k) if @options[:plaintext]
        elsif @options[:ciphertext]
          @cipher.decrypt(@options[:ciphertext], k) if @options[:ciphertext]
        else
        end
      puts "calc result: #{@result}" if @options[:debug]
    rescue Exception => pf
      STDOUT.puts "Could not decrypt ciphertext: #{pf.message}"
      puts pf.backtrace * "\n" if @options[:debug]
      exit -1
    end
    (@results ||= []) << @result
  end
end

print_result(@results) if @results

@cipher ||= ToyCipher::ToyCipherBase.new

if @options[:analysis] 
  if @options[:decrypt]
    @cipher.frequency @options[:ciphertext]
  elsif @options[:encrypt]
    @cipher.frequency @options[:plaintext]
  elsif @stdin
    @cipher.frequency @stdin
  elsif @input
    @cipher.frequency @input
  end
end


